export const apiNames = {
  "admin-session": "Administrative Sessions",
  "api-key": "API Keys",
  "attribute": "Attributes",
  "billing": "Billing",
  "client-connect": "Client Connect",
  "event": "Events",
  "game-server": "Game Servers",
  "integration": "Integrations",
  "lobby": "Game Lobbies",
  "nat-punchthrough": "NAT Punchthrough",
  "netcode": "netcode.io",
  "pos": "Point of Sale",
  "presence": "Presence",
  "reporting": "Reporting",
  "revenue-share": "Revenue Share",
  "search": "Search",
  "scheduling": "Scheduling",
  "temp-session": "Temporary Sessions",
  "ugc-cache": "UGC Cache",
  "user-session": "User Sessions",
};