set(CMAKE_C_FLAGS "-m64" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "-m64" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "-m64" CACHE STRING "" FORCE)
set(CMAKE_STATIC_LINKER_FLAGS "-m64" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "-m64" CACHE STRING "" FORCE)

set(OPENSSL_INCLUDE_DIR /usr/include/x86_64-linux-gnu)
set(OPENSSL_ROOT_DIR "/usr/lib/x86_64-linux-gnu" CACHE STRING "" FORCE)