export { getSdkSetup } from './fragments/sdk';
export { getExceptionClass } from './fragments/exception';
export { getHttpClientClass } from './fragments/httpClient';
export { getDefines } from './fragments/defines';
export { namespaceBegin, namespaceEnd } from './fragments/namespace';
export { interfacePrefix, interfaceSuffix } from './fragments/controllerInterface';
export { implementationPrefix, implementationSuffix } from './fragments/controllerImplementation';
export { interfaceMethodDeclarations, implementationMethodDeclarations } from './fragments/methods';
export { getPromiseClass } from './fragments/promise';

export function getCodePrefix(defines: string[]) {
  return `
//------------------------
// <auto-generated>
//     Generated with HiveMP SDK Generator
// </auto-generated>
//------------------------

${defines.join("\n")}

`;
}