export { getSdkSetup } from './fragments/sdk';
export { getExceptionClass } from './fragments/exception';
export { getHttpClientClass } from './fragments/httpClient';
export { getDefines } from './fragments/defines';
export { namespaceBegin, namespaceEnd } from './fragments/namespace';
export { interfacePrefix, interfaceSuffix } from './fragments/controllerInterface';
export { implementationPrefix, implementationSuffix } from './fragments/controllerImplementation';
export { 
  interfaceMethodDeclarations, 
  interfaceWebSocketMethodDeclarations,
  implementationMethodDeclarations, 
  implementationWebSocketMethodDeclarations 
} from './fragments/methods';
export { getPromiseMainThreadReturnClass, getPromiseSchedulerSettingsClass } from './fragments/promise';
export { getWebSocketClass } from './fragments/websocket';

export function getCodePrefix(defines: string[]) {
  return `
//------------------------
// <auto-generated>
//     Generated with HiveMP SDK Generator
// </auto-generated>
//------------------------

${defines.join("\n")}

`;
}