export function getExceptionClass(defines: string[]) {
  return `
//------------------------
// <auto-generated>
//     Generated with HiveMP SDK Generator
// </auto-generated>
//------------------------

${defines.join("\n")}

using System;
using System.IO;
using System.Threading;

namespace HiveMP.Api
{
    public class HiveMPException : Exception
    {
        static HiveMPException()
        {
            HiveMP.Api.HiveMPSDK.EnsureInited();
        }

        public HiveMPException(int httpStatusCode, HiveMPSystemError error)
            : base(GenerateMessageFromError(error))
        {
            HttpStatusCode = httpStatusCode;
            Error = error;
        }

        private static string GenerateMessageFromError(HiveMPSystemError error)
        {
            var errorCode = 0;
            var errorMessage = "";
            var errorFields = "";
            if (error != null)
            {
                errorCode = error.Code ?? 0;
                if (error.Message != null)
                {
                    errorMessage = error.Message;
                }
                if (error.Fields != null)
                {
                    errorFields = error.Fields;
                }
            }
            return "#" + errorCode + ": " + errorMessage + " (" + errorFields + ")";
        }

        public int HttpStatusCode { get; set; }

        public HiveMPSystemError Error { get; set; }
    }
}    
`;
}