#include "embed.h"
const char* _embedded_sdk = "/******/ (function(modules) { // webpackBootstrap\n"
  "/******/ 	// The module cache\n"
  "/******/ 	var installedModules = {};\n"
  "/******/\n"
  "/******/ 	// The require function\n"
  "/******/ 	function __webpack_require__(moduleId) {\n"
  "/******/\n"
  "/******/ 		// Check if module is in cache\n"
  "/******/ 		if(installedModules[moduleId]) {\n"
  "/******/ 			return installedModules[moduleId].exports;\n"
  "/******/ 		}\n"
  "/******/ 		// Create a new module (and put it into the cache)\n"
  "/******/ 		var module = installedModules[moduleId] = {\n"
  "/******/ 			i: moduleId,\n"
  "/******/ 			l: false,\n"
  "/******/ 			exports: {}\n"
  "/******/ 		};\n"
  "/******/\n"
  "/******/ 		// Execute the module function\n"
  "/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);\n"
  "/******/\n"
  "/******/ 		// Flag the module as loaded\n"
  "/******/ 		module.l = true;\n"
  "/******/\n"
  "/******/ 		// Return the exports of the module\n"
  "/******/ 		return module.exports;\n"
  "/******/ 	}\n"
  "/******/\n"
  "/******/\n"
  "/******/ 	// expose the modules object (__webpack_modules__)\n"
  "/******/ 	__webpack_require__.m = modules;\n"
  "/******/\n"
  "/******/ 	// expose the module cache\n"
  "/******/ 	__webpack_require__.c = installedModules;\n"
  "/******/\n"
  "/******/ 	// define getter function for harmony exports\n"
  "/******/ 	__webpack_require__.d = function(exports, name, getter) {\n"
  "/******/ 		if(!__webpack_require__.o(exports, name)) {\n"
  "/******/ 			Object.defineProperty(exports, name, {\n"
  "/******/ 				configurable: false,\n"
  "/******/ 				enumerable: true,\n"
  "/******/ 				get: getter\n"
  "/******/ 			});\n"
  "/******/ 		}\n"
  "/******/ 	};\n"
  "/******/\n"
  "/******/ 	// define __esModule on exports\n"
  "/******/ 	__webpack_require__.r = function(exports) {\n"
  "/******/ 		Object.defineProperty(exports, '__esModule', { value: true });\n"
  "/******/ 	};\n"
  "/******/\n"
  "/******/ 	// getDefaultExport function for compatibility with non-harmony modules\n"
  "/******/ 	__webpack_require__.n = function(module) {\n"
  "/******/ 		var getter = module && module.__esModule ?\n"
  "/******/ 			function getDefault() { return module['default']; } :\n"
  "/******/ 			function getModuleExports() { return module; };\n"
  "/******/ 		__webpack_require__.d(getter, 'a', getter);\n"
  "/******/ 		return getter;\n"
  "/******/ 	};\n"
  "/******/\n"
  "/******/ 	// Object.prototype.hasOwnProperty.call\n"
  "/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };\n"
  "/******/\n"
  "/******/ 	// __webpack_public_path__\n"
  "/******/ 	__webpack_require__.p = \"\";\n"
  "/******/\n"
  "/******/\n"
  "/******/ 	// Load entry module and return exports\n"
  "/******/ 	return __webpack_require__(__webpack_require__.s = \"./src/index.ts\");\n"
  "/******/ })\n"
  "/************************************************************************/\n"
  "/******/ ({\n"
  "\n"
  "/***/ \"./src/index.ts\":\n"
  "eval(\"\\r\\nObject.defineProperty(exports, \\\"__esModule\\\", { value: true });\\r\\nvar timers = __webpack_require__(/*! timers */ \\\"timers\\\");\\r\\nvar console = __webpack_require__(/*! console */ \\\"console\\\");\\r\\ntimers.setTimeout(function () {\\r\\n    console.log(\\\"hello\\\");\\r\\n}, 2000);\\r\\n/*\\r\\n\\r\\nfunction testHook(request: IHotpatchRequest): IHotpatchResponse {\\r\\n  return {\\r\\n    code: 201,\\r\\n    response: {\\r\\n      test: \\\"hello\\\",\\r\\n      what: [\\r\\n        \\\"even\\\",\\r\\n        { is: \\\"this\\\" }\\r\\n      ]\\r\\n    }\\r\\n  }\\r\\n}\\r\\n\\r\\nregister_hotpatch(\\\"temp-session:sessionPUT\\\", testHook);\\r\\n\\r\\n*/ \\r\\n\\n\\n//# sourceURL=webpack:///./src/index.ts?\");,\n"
  "\n"
  "/***/ \"console\":\n"
  "eval(\"module.exports = require(\\\"console\\\");\\n\\n//# sourceURL=webpack:///external_%22console%22?\");,\n"
  "\n"
  "/***/ \"timers\":\n"
  "eval(\"module.exports = require(\\\"timers\\\");\\n\\n//# sourceURL=webpack:///external_%22timers%22?\");\n"
  "\n"
  "/******/ });";
